# Generated by Django 4.2.6 on 2023-11-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('acupation', models.CharField(max_length=100)),
                ('planet', models.CharField(max_length=100)),
                ('first_appearance', models.DateField()),
            ],
        ),
    ]
