# Generated by Django 4.2.7 on 2023-11-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character_is_live_alter_character_first_appearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='is_live',
        ),
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.ImageField(null=True, upload_to='character'),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(default='default value', max_length=150),
        ),
    ]
